routes/web.php
    Route::get('/order/list/show/{id}', 'App\Http\Controllers\OrderListController@showPendingRequest')->name('pendingOrder.show');
    Route::post('/order/update/{id}', 'App\Http\Controllers\OrderListController@updatePendingRequest')->name('pendingOrder.update');
    Route::post('/order/replace/{id}', 'App\Http\Controllers\OrderListController@replacePendingRequest')->name('pendingOrder.replace');

    Route::resource('shop-item-issue', 'App\Http\Controllers\ShopItemIssueController');
    Route::post('shop-item-issue/{loading_data_raw}/load', 'App\Http\Controllers\ShopItemIssueController@issueRawMaterial');
    Route::get('shop-item-issue/table/data', 'App\Http\Controllers\ShopItemIssueController@tableData')->name('shop-item-issue.table');

    Route::get('loading/table/revers', 'LoadingManager\Controllers\LoadingController@revers')->name('loading.revers');

    Route::get('loading/table/data', 'LoadingManager\Controllers\LoadingController@tableData')->name('loading.table');
    Route::get('loading/table/view', 'LoadingManager\Controllers\LoadingController@showTable')->name('loading.stable');
    Route::get('sales/return/data', 'LoadingManager\Controllers\LoadingController@SalesReturnData')->name('loading.sales-return-data');



    Route::post('loading/with-discount/generate/bill', 'LoadingManager\Controllers\LoadingController@withDiscount')->name('loading.discount');
    Route::post('loading/with-discount/generate/pdf', 'LoadingManager\Controllers\LoadingController@printDiscount')->name('loading.dpdf');
    Route::get('generate/{id}/pdf', 'LoadingManager\Controllers\LoadingController@printDiscount')->name('loading.gpdf');

    Route::resource('crates-return', 'App\Http\Controllers\CratesReturnController');
    Route::get('crates-return/table/data', 'App\Http\Controllers\CratesReturnController@tableData')->name('crates-return.table');

    Route::resource('end-product-merge-list', 'App\Http\Controllers\EndProductBurdenMergeController');
    Route::get('end-product-merge-list/table/data', 'App\Http\Controllers\EndProductBurdenMergeController@tableData')->name('crates-return.table');
    Route::delete('end-product-burden/delete}', 'App\Http\Controllers\EndProductBurdenMergeController@deleteBurden')->name('end-b.delete');


    Route::get('agent/outstanding', 'App\Http\Controllers\AgentOutstandingController@index')->name('outstanding.index');
    Route::get('agent/outstanding/table/data', 'App\Http\Controllers\AgentOutstandingController@tableData')->name('outstanding.table');
    Route::get('agent/pay/{id}/force', 'App\Http\Controllers\AgentOutstandingController@forcePay')->name('outstanding.force');

    Route::post('reports/mgvsl', 'App\Http\Controllers\MergeVsLoadedController@getItems')->name('mgvsl.items');


    Route::get('reports/end-product/movements', 'App\Http\Controllers\EndProductMovementReport@index')->name('reports.end-move');
    Route::get('/reports/end-product/movements/table/data', 'App\Http\Controllers\EndProductMovementReport@tableData')->name('reports.end-move-table');
    Route::get('/reports/end-product/movements/table/sales/data', 'App\Http\Controllers\EndProductMovementReport@tableDataSales')->name('reports.end-move-table-sales');
    Route::get('/reports/end-product/movements/table/return/data', 'App\Http\Controllers\EndProductMovementReport@tableDataReturns')->name('reports.end-move-table-return');


    Route::resource('numbers', 'App\Http\Controllers\NumberController');
    Route::post('numbers/assign/user', 'App\Http\Controllers\NumberController@assign')->name('numbers.assign');
    Route::get('/delete/user/number/{id}', 'App\Http\Controllers\NumberController@deleteUserNumber')->name('numbers.delete');
    Route::get('/delete/number/{id}', 'App\Http\Controllers\NumberController@deleteNumber')->name('number.delete');
    Route::get('/edit/number/{id}', 'App\Http\Controllers\NumberController@updateNumber')->name('number.update');
    Route::post('/change/user/number/{id}', 'App\Http\Controllers\NumberController@changeStatus')->name('number.status');


    Route::get('supplier/outstanding/data', 'App\Http\Controllers\SupplierOutstandingController@index')->name('supplier-outstanding.index');
    Route::get('supplier/outstanding/table/data', 'App\Http\Controllers\SupplierOutstandingController@tableData')->name('supplier-outstanding.table');


    Route::get('cash/inquiry', 'App\Http\Controllers\CashBookInquiryController@index')->name('cash-inquiry.index');
    Route::get('end/product/history', 'App\Http\Controllers\EndProductBurdenMergeController@endProductBurdenList')->name('end-product.history');


    Route::get('view-history/{burden}', 'App\Http\Controllers\EndProductBurdenMergeController@show_end_product')->name('end-burden.show');


    Route::get('end/product/history/table', 'App\Http\Controllers\EndProductBurdenMergeController@endProductHistoryData')->name('end-product.history-data');
    Route::get('cash/inquiry/table/data', 'App\Http\Controllers\CashBookInquiryController@tableData')->name('cash-inquiry.table');
    Route::get('cash/inquiry/table/summery', 'App\Http\Controllers\CashBookInquiryController@tableSum')->name('cash-inquiry.summery');

    Route::get('raw/request', 'App\Http\Controllers\RawMaterialIssueController@rawIndex')->name('raw-request.index');
    Route::get('raw/request/store', 'App\Http\Controllers\RawMaterialIssueController@rawStore')->name('raw-request.store');
    Route::get('raw/issue/store', 'App\Http\Controllers\RawMaterialIssueController@rawIssue')->name('raw-issue.stores');
    Route::get('raw/request/print/{ref}', 'App\Http\Controllers\RawMaterialIssueController@print')->name('ppcc.show');


//============================================= ProductionController =============================================
    Route::get('production', 'App\Http\Controllers\ProductionController@index')->name('production.index');
    Route::get('production/sales/request', 'App\Http\Controllers\ProductionController@salesRequestTableData')->name('production.sales');

    Route::post('production/sr/cal/pro', 'App\Http\Controllers\ProductionController@mergeSalesRequests')->name('production.create');
    Route::post('production/sr/cal/pro/to/burden', 'App\Http\Controllers\ProductionController@salesRequestsToBurden')->name('production.burden');

    Route::get('production/merged/request', 'App\Http\Controllers\ProductionController@mergedSalesRequests')->name('production.merged');
    Route::get('production/sr/end/burden/list', 'App\Http\Controllers\ProductionController@endBurdenList')->name('production.burdens');

    Route::post('production/burden/merge', 'App\Http\Controllers\ProductionController@mergeBurdens')->name('pburden.merge');
    Route::get('production/issue/semi/{id}', 'App\Http\Controllers\ProductionController@issueSemi')->name('issue.semi');

    Route::Post('production/make/semi/{id}', 'App\Http\Controllers\ProductionController@makeSemiBurden')->name('make.semi');
    Route::Post('production/make/cooking/{id}', 'App\Http\Controllers\ProductionController@makeSemiBurdenCooking')->name('make.semi');
    Route::Post('production/create/semi/{id}', 'App\Http\Controllers\ProductionController@createSemiBurden')->name('create.semi');
    Route::Post('production/create/cooking/{id}', 'App\Http\Controllers\ProductionController@createSemiBurdenCooking')->name('create.semi');


    Route::Post('production/semi/issue/store', 'App\Http\Controllers\ProductionController@semiIssue')->name('create.semi');
    Route::get('production/sales/order/list/{id}', 'App\Http\Controllers\ProductionController@salesLoadingList')->name('pro.loading');

    Route::get('sr/merge/list', 'App\Http\Controllers\ProductionController@srMergeList')->name('sr.list');
    Route::get('ep/merge/list', 'App\Http\Controllers\ProductionController@epMergeList')->name('ep.list');


    Route::get('merged/sales/requests/{id}', 'App\Http\Controllers\ProductionController@mergedSalesRequestList')->name('merged.list');
    Route::get('merged/sales/delete/{id}', 'App\Http\Controllers\ProductionController@mergedSalesHeaderDelete')->name('merged.delete');

    Route::get('bulk/burden/make/merged/{id}', 'App\Http\Controllers\ProductionController@semiBulk')->name('semi.bulk');
    Route::get('bulk/burden/end/merged/{id}', 'App\Http\Controllers\ProductionController@endBulk')->name('end.bulk');

    Route::post('bulk/production/burden/store', 'App\Http\Controllers\ProductionController@bulkBurdenStage')->name('production_burden.store');
    Route::post('bulk/production/cooking/store', 'App\Http\Controllers\ProductionController@bulkCookingStage')->name('production_cook.store');
    Route::post('bulk/production/end/store', 'App\Http\Controllers\ProductionController@bulkEndStage')->name('production_end.store');


    Route::get('production/semi/diff/issue/{id}', 'App\Http\Controllers\ProductionController@differenceIssue')->name('production.diff');
    Route::get('production/adjust/semi/{id}', 'App\Http\Controllers\ProductionController@adjustSemi')->name('adjust.semi');
    Route::Post('production/adjust/semi/issue/store', 'App\Http\Controllers\ProductionController@adjustSemiBalance')->name('adjust.semiB');

    Route::get('production/vs/accept/{id}', 'App\Http\Controllers\ProductionController@ProductionVsAccept')->name('production.vs');
    Route::post('production/vs/accept', 'App\Http\Controllers\ProductionController@productionAdjust')->name('production.vss');
    Route::get('production/currant/balance/{id}', 'App\Http\Controllers\ProductionController@endProductCurrantBalance')->name('production.currantB');
    Route::post('production/currant/balance/update', 'App\Http\Controllers\ProductionController@endProductCurrantBalanceUpdate')->name('production.cuBal');


    Route::get('production/approve/admin/{id}', 'App\Http\Controllers\ProductionController@adminApprove')->name('production.approve');


    Route::get('agent/sales/return/', 'App\Http\Controllers\AgentSalesReturnController@index')->name('agent.return');

app/Number.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Number extends Model
{
    protected $fillable=['number','description'];
    public function users(){
        return $this->belongsToMany(\UserManager\Models\Users::class);
    }
}

app/Http/Controllers/NumberController.php
<?php

namespace App\Http\Controllers;

use App\Number;
use App\User;
use App\UserNumber;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NumberController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:number-index', ['only' => ['index']]);
        $this->middleware('permission:number-list', ['only' => ['list']]);
        $this->middleware('permission:number-store', ['only' => ['store']]);
        $this->middleware('permission:number-delete', ['only' => ['deleteUserNumber']]);

    }
    public function index()
    {
        $numbers = Number::all();
        $number_list = Number::pluck('number', 'id');
        $users = User::pluck('email', 'id');
        $list = UserNumber::all();
        return view('numbers.create', compact('numbers', 'number_list', 'users', 'list'));
    }

    public function store(Request $request)
    {
        $num = new Number();
        $num->number = $request->number;
        $num->description = $request->description;
        $num->save();
        return redirect()->route('numbers.index')->with([
            'success' => true,
            'success.title' => 'Congratulations !',
            'success.message' => 'You have entered a number',
        ]);
    }

    public function updateNumber(Request $request)
    {

    }

    public function changeStatus(Request $request){
       $number_data = $request->id;
       $type = $request->type;
       $data =UserNumber::find($number_data);
       $data->status = $type;
       $data->save();
       return 1;

    }

    public function deleteNumber(Request $request)
    {
        $number_id = $request->id;
        $numbers = UserNumber::whereNumberId($number_id)->get();
        if (!empty($numbers) && $numbers->count() > 0) {
            return redirect()->back()->with([
                'error' => true,
                'error.title' => 'Sorry',
                'error.message' => 'You have assigned this number to users',
            ]);
        }

        $number = Number::find($request->id);
        $number->delete();
        return redirect()->route('numbers.index')->with([
            'success' => true,
            'success.title' => 'Oh !',
            'success.message' => 'You have deleted a number',
        ]);

    }


    public function assign(Request $request)
    {
        $user = User::find($request->user);
        $number = Number::find($request->number);

        $exsist = UserNumber::whereUserId($user->id)->whereNumberId($number->id)->get();
        if (!empty($exsist) && $exsist->count() > 0) {
            return redirect()->route('numbers.index')->with([
                'error' => true,
                'error.title' => 'Sorry',
                'error.message' => 'Record Already Exist !',
            ]);
        }
        $con = new UserNumber();
        $con->user_id = $user->id;
        $con->number_id = $number->id;
        $con->created_by = Auth::user()->id;
        $con->save();
        return redirect()->route('numbers.index');
    }

    public function deleteUserNumber(Request $request)
    {
        $list = UserNumber::find($request->id);
        if ($role = Sentinel::check()->roles[0]->slug == 'owner') {
            $list->delete();
        } else {
            return redirect()->back()->with([
                'error' => true,
                'error.title' => 'Sorry',
                'error.message' => 'You Have Not Permissions To Delete Records',
            ]);
        }
        return redirect()->route('numbers.index');
    }
}

resources/views/numbers/create.blade.php
@extends('layouts.back.master')@section('title','Numbers')
@section('css')

    <meta name="_token" content="{{ csrf_token() }}"/>
    <link rel="stylesheet" href="{{asset('assets/examples/css/apps/projects.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/examples/css/demos/form.wizard.css')}}">
    <link rel="stylesheet" href="{{asset('assets/vendor/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('assets/examples/css/apps/modal.css')}}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css"/>
    <link rel="stylesheet" href="{{asset('assets/examples/css/demos/demos.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/examples/css/dashboards/dashboard.v1.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/css/site.css')}}"/>
    <link rel="stylesheet"
          href="{{asset('assets/vendor/bower_components/perfect-scrollbar/css/perfect-scrollbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/packages/recipe/recipe.css')}}">


    <style>
        .hide {
            display: none;
        }

        .floating-button {
            width: 35px;
            height: 35px;
            border-radius: 50%;
            background: #60c84c;
            position: fixed;

            cursor: pointer;
            box-shadow: 0px 2px 5px #666;
            z-index: 2
        }

        .plus {
            color: white;
            position: absolute;
            top: 0;
            display: block;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            padding: 0;
            margin: 0;
            line-height: 35px;
            font-size: 38px;
            font-family: 'Roboto';
            font-weight: 300;
            animation: plus-out 0.3s;
            transition: all 0.3s;
        }


    </style>
@stop
@section('content')
@section('current','Numbers')
@section('current_url',route('numbers.index'))
<div class="app-wrapper">
    <div class="app-panel" id="app-panel">

        <div class="app-panel-inner">
            <div class="scroll-container">
                <div class="p-3">
                    <button class="btn btn-warning py-3 btn-block btn-lg" data-toggle="modal"
                            data-target="#cat">NEW NUMBER
                    </button>
                </div>
                <hr class="m-0">
                <div class="p-3">
                    <button class="btn btn-outline-danger py-3 btn-block btn-lg" data-toggle="modal"
                            data-target="#assign">Assign NUMBER
                    </button>
                </div>
                <hr class="m-0">
                <div class="projects-list">
                    @foreach($numbers as $number)
                        <a>
                            <div class="panel-item media p-2 mb-2">
                                <div class="media-body">
                                    <h6 class="media-heading my-1">
                                        {{$number->number}}
{{--                                        <a class="float-right" href="/edit/number/{{$number->id}}"> <i class="fa fa-pencil mr-2 text-indigo"></i></a>--}}
                                    </h6>
                                    <i class="qty-icon fa fa-archive"></i>
                                    <small>{{$number->description}}</small>
                                    <a class="float-right" href="/delete/number/{{$number->id}}"> <i class="fa fa-close  mr-2 text-danger"></i></a>
                                    <br>
                                    </div>
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
        <a href="#" class="app-panel-toggle" data-toggle="class" data-target="#app-panel" data-class="show"><i
                    class="fa fa-chevron-right"></i>
            <i class="fa fa-chevron-left"></i>
        </a>
    </div>

    <div class="app-main">
        <div class="app-main-header">
            <h5 class="app-main-heading text-center">Numbers</h5>
        </div>
        <div class="app-main-content px-3 py-4" style="background-color: white" id="container">
            <div class="content ">
                <div class="contacts-list">
                    @foreach($list as $item)
                        @php
                            $btn_cls= $item->status?'btn-success':'btn-danger';
$btn_text =$item->status?'Active':'Disabled'
                        @endphp
                        <div class="panel-item media mb-2">
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-md-3">{{optional($item->number)->number}}</div>
                                    <div class="col-md-3">{{!empty(App\User::find($item->user_id))?\App\User::find($item->user_id)->email:'User Deleted'}}</div>
                                    <div class="col-md-2">
                                        <button class="btn  btn-sm {{$btn_cls}}">{{$btn_text}}</button>
                                    </div>
                                    <div class="col-md-2">
                                        <input type="checkbox" class="one text-center" onclick="changeStatus(this,{{$item->id}})" data-size="medium" value="{{($item->status==1)?1:0 }}" {{($item->status==1) ?'checked':null }} >
                                    </div>
                                    <div class="col-md-2 text-right"><a href="/delete/user/number/{{$item->id}}"> <i class="fa fa-close text-danger"></i></a></div>
                                </div>
                                <br>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="cat" tabindex="-1" role="dialog" aria-divledby="myModaldiv"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-div="Close">
                    <span aria-hidden="true"><i class="zmdi zmdi-close"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-lg-12">
                    <div class="card">
                        {{ Form::open(array('url' => route('numbers.store'),'enctype'=>'multipart/form-data'))}}
                        <div class="wizard p-4" id="bootstrap-wizard-1">
                            <ul class="nav nav-tabs vertices keep-prefix-suffix" role="tablist">
                                <li class="nav-item">
                                    <a class=" nav-link active" data-toggle="tab" href="#ex5-step-1"
                                       role="tab">
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="ex5-step-1" role="tabpanel">


                                    <div class="task-name-wrap">
                                        <span style="top: 15px;"><i class="zmdi zmdi-check"></i></span>
                                        <input class="task-name-field" type="number" name="number"
                                               placeholder="Number">
                                    </div>

                                    <hr>
                                    <div class="task-name-wrap">
                                        <span style="top: 15px;"><i class="zmdi zmdi-check"></i></span>
                                        <input class="task-name-field" type="text" name="description"
                                               placeholder="Description">
                                    </div>

                                </div>
                            </div>
                            <div class="pager d-flex justify-content-center">
                                <input type="submit" id="finish-btn" class="finish btn btn-success btn-block"
                                       value="Finish">
                            </div>
                        </div>
                        {!!Form::close()!!}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="assign" tabindex="-1" role="dialog" aria-divledby="myModaldiv"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-div="Close">
                    <span aria-hidden="true"><i class="zmdi zmdi-close"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-lg-12">
                    <div class="card">
                        {{ Form::open(array('url' => route('numbers.assign'),'enctype'=>'multipart/form-data'))}}
                        <div class="wizard p-4" id="bootstrap-wizard-1">
                            <ul class="nav nav-tabs vertices keep-prefix-suffix" role="tablist">
                                <li class="nav-item">
                                    <a class=" nav-link active" data-toggle="tab" href="#ex5-step-1"
                                       role="tab">
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="ex5-step-1" role="tabpanel">


                                    <div class="task-name-wrap">
                                        <span style="top: 15px;"><i class="zmdi zmdi-check"></i></span>
                                        {!! Form::select('user', $users , null , ['class' => 'task-name-field','placeholder'=>'Select User']) !!}
                                    </div>

                                    <hr>
                                    <div class="task-name-wrap">
                                        <span style="top: 15px;"><i class="zmdi zmdi-check"></i></span>
                                        {!! Form::select('number', $number_list , null , ['class' => 'task-name-field','placeholder'=>'Select Number']) !!}
                                    </div>

                                </div>
                            </div>
                            <div class="pager d-flex justify-content-center">
                                <input type="submit" id="finish-btn" class="finish btn btn-success btn-block"
                                       value="Finish">
                            </div>
                        </div>
                        {!!Form::close()!!}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


@stop
@section('js')
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {{--    <script src="{{asset('assets/examples/js/apps/projects.js')}}"></script>--}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
    <script src="{{asset('assets/vendor/bower_components/jquery-validation/dist/jquery.validate.min.js')}}"></script>
    <script src="{{asset('assets/vendor/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/vendor/bower_components/twitter-bootstrap-wizard/jquery.bootstrap.wizard.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <script src="{{asset('assets/vendor/bower_components/perfect-scrollbar/js/perfect-scrollbar.js')}}"></script>
    <script src="{{asset('assets/packages/semi_finish/semi_finish.js')}}"></script>
    <script src="{{asset('assets/packages/recipe/end-recipe.js')}}"></script>
    <script>
        function changeStatus(element,id){
            let type =null;

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });

            if($(element).prop("checked") == true){
                type =1
            }
            else if($(element).prop("checked") == false){
                type =0;
            }

            $.ajax({
                url: "/change/user/number/"+id,
                data: {
                    "type": type,
                },
                cache: false,
                type: "POST",
                success: function(response) {

                },
                error: function(xhr) {

                }
            });
        }
    </script>
@stop